dist: jammy
language: go
group: edge

before_script:
 - chmod u+x step.sh 
 
script: 
 - wget https://dl.step.sm/gh-release/cli/docs-cli-install/v0.20.0/step-cli_0.20.0_amd64.deb
 - sudo dpkg -i step-cli_0.20.0_amd64.deb
 - step -v 
 - step certificate create --profile root-ca "Montana Mendy Travis CI keys" ca.crt ca.key < ./step.sh 
 - ./step.sh 
